### ISSUE TITLE
NewConnection should not return token

### ISSUE THREAD

**Issue by andig** [WulfgarW/sensonet#3]
It's not it's task

**Comment by Bronze09876** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by andig** [comment]
Spam...

**Comment by WulfgarW** [comment]
NewConnection() shall encapsulate the whole initialisation of the connection to the myVaillant portal. So NewIdentity should be private, and NewConnection returns the Connection struct, the oauth2.Token and error information.

**Comment by andig** [comment]
It shouldn't because this removes composability (Separation of concerns). Even if- in this case NewIdentity should become private. NewConnection MUST not return a token because that's private to the conneciton. If you think tokens are relevant, split Connection and Identity.
