### ISSUE TITLE
Add a logger interface

### ISSUE THREAD

**Issue by andig** [WulfgarW/sensonet#7]
Currently consumers cannot override the logging behavior

**Comment by WulfgarW** [comment]
@andig 
Consumers can set the logging behaviour via the http.Client they pass to NewConnection().
Only the logging behaviour of the http.Client used for the token refresher can not be changed by consumers. Do you think, a logger interface for the token refresher is necessary, or should this logging be suppressed.

**Comment by andig** [comment]
The cant because log is being used as well!

**Comment by andig** [comment]
Einfacher als der aktuelle Code wäre es hier, auf nil zu prüfen:

```go
			if _, ok := logger.(Logger); ok {
				logger.Debug(fmt.Sprintf("Old quickmode: \"%s\"   New quickmode: \"%s\"", c.currentQuickmode, newQuickMode))
			}
```

Die Variable kann ja nur vom Typ `Logger` sein, wenn != nil ist das also immer ok. `NewLogger` sollte dann `SetLogger` heissen. 


Um das nicht überall zu wiederholen würde man

```go
func (conn *Connection) debug(fmt string, arg ...any) {
    if conn.logger != nil {
        // ...
    }
}
```

machen. 


Das Logger Interface selbst kann ausgedünnt werden um die Implementierung zu erleichtern- `Printf` schiene zu reichen?

Noch schöner wäre es, das als Konfigurationsoption der Connection auszuprägen. Viele Libraries verwenden dafür dieses Pattern:

    sensonet.NewConnection(client, ts, sensonet.WithLogger(logger))

**Comment by WulfgarW** [comment]
Ich hatte überlegt, ob der Logger auch außerhalb der Klasse Connection innerhalb des sensonet-Packages zur Verfügung stehen sollte. Aber da ich aktuell keinen Bedarf sehe, habe ich ihn jetzt entsprechend Deinem Vorschlag umgesetzt.

**Comment by WulfgarW** [comment]
Fixed by commit e3daa66
